---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spidey-stage
  namespace: webby-stage
spec:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        name: spidey-stage
    spec:
      containers:
      - name: spidey-stage
        image: undeadops/webby:master-f619e5d
        env:
        - name: K8S_CLUSTER
          value: "whiskey"
        - name: FOO
          value: "bar"
        ports:
        - name: http-api
          containerPort: 5000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
