apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spidey-stage
  namespace: webby-stage
spec:
  minReadySeconds: 5
  selector: null
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: spidey-stage
    spec:
      containers:
      - env:
        - name: K8S_CLUSTER
          value: whiskey
        - name: FOO
          value: bar
        image: undeadops/webby:master-4df3334
        name: spidey-stage
        ports:
        - containerPort: 5000
          name: http-api
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
status: {}
